name = "voice-translator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Workers AI binding
[ai]
binding = "AI"

# Durable Object for conversation memory
[[durable_objects.bindings]]
name = "CONVERSATION_MEMORY"
class_name = "ConversationMemory"
script_name = "voice-translator"

[[migrations]]
tag = "v1"
new_classes = ["ConversationMemory"]

# KV namespace for additional storage
[[kv_namespaces]]
binding = "TRANSLATION_CACHE"
id = "preview_id"
preview_id = "preview_id"

# Environment variables
[vars]
ENVIRONMENT = "production"
